version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    container_name: frontend_web_container
    image: frontend_web_image:0.1.0
    ports: 
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: frontend_test_container
    image: frontend_tests_image:0.1.0
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]