version: '3'
services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: frontend_container
    image: frontend_image:1.0.0
    ports: 
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./src/App.js:/app/src/App.js